swagger: '2.0'
info:
  description: CoffeeQuiz API
  version: 1.0.0
  title: CoffeeQuiz
  termsOfService: 'https://coffeequiz.azurewebsites.net/terms'
  contact:
    email: oyron@equinor.com
  license:
    name: GNU GPLv3
    url: 'https://choosealicense.com/licenses/gpl-3.0/'
host: 'coffeequiz.azurewebsites.net'
basePath: /api/v1.0
tags:
  - name: quiz
    description: Everything about Quiz
schemes:
  - https
  - http
paths:
  /quiz:
    get:
      tags:
        - quiz
      summary: Finds all quizes
      description: Multiple status values can be provided with comma separated strings
      operationId: getQuizes
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Quiz'
        '400':
          description: Invalid status value
  
definitions:
  Quiz:
    type: object
    required:
      - name
      - photoUrls
    properties:
      _id:
        type: string
      name:
        type: string
      quizItems:
        type: string
      startTime:
        type: string
      sequenceNumber:
        type: integer
        format: int64
      createdBy:
        type: string
      phase:
        type: string
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
